#pragma once

#include "../board_caps.h"

#define BOARD_NAME "Generic ESP32-C3"

#define DEFAULT_DEBUG_UART_NUM     UART_NUM_0
#define DEFAULT_DEBUG_UART_TX_PIN  GPIO_NUM_21
#define DEFAULT_DEBUG_UART_RX_PIN  GPIO_NUM_20
#define DEFAULT_DEBUG_UART_RTS_PIN GPIO_NUM_NC
#define DEFAULT_DEBUG_UART_CTS_PIN GPIO_NUM_NC

#define BOARD_HAS_ETHERNET   0
#define BOARD_HAS_WIFI       1
#define BOARD_HAS_BLUETOOTH  1
#define BOARD_HAS_SD         0
#define BOARD_HAS_LORA_UART  0
#define BOARD_HAS_GNSS_UART  0
#define BOARD_ETHERNET_TYPE  BOARD_ETHERNET_TYPE_NONE

#define BOARD_NTRIP_MAX_SLOTS_NO_PSRAM 1
#define BOARD_NTRIP_MAX_SLOTS_PSRAM    2
