#pragma once

#include "../board_caps.h"

#define BOARD_NAME "Waveshare ESP32-S3-ETH"

#define DEFAULT_DEBUG_UART_NUM     UART_NUM_0
#define DEFAULT_DEBUG_UART_TX_PIN  GPIO_NUM_43
#define DEFAULT_DEBUG_UART_RX_PIN  GPIO_NUM_44
#define DEFAULT_DEBUG_UART_RTS_PIN GPIO_NUM_16
#define DEFAULT_DEBUG_UART_CTS_PIN GPIO_NUM_17

#define DEFAULT_GNSS_UART_NUM      UART_NUM_1
#define DEFAULT_GNSS_UART_TX_PIN   GPIO_NUM_1
#define DEFAULT_GNSS_UART_RX_PIN   GPIO_NUM_2
#define DEFAULT_GNSS_UART_RTS_PIN  GPIO_NUM_15
#define DEFAULT_GNSS_UART_CTS_PIN  GPIO_NUM_18

#define DEFAULT_AUX_UART_NUM       UART_NUM_2
#define DEFAULT_AUX_UART_TX_PIN    GPIO_NUM_37
#define DEFAULT_AUX_UART_RX_PIN    GPIO_NUM_38
#define DEFAULT_AUX_UART_RTS_PIN   GPIO_NUM_39
#define DEFAULT_AUX_UART_CTS_PIN   GPIO_NUM_40

#define BOARD_ETH_MOSI             GPIO_NUM_11
#define BOARD_ETH_MISO             GPIO_NUM_12
#define BOARD_ETH_SCLK             GPIO_NUM_13
#define BOARD_ETH_CS               GPIO_NUM_14
#define BOARD_ETH_INT              GPIO_NUM_10
#define BOARD_ETH_RST              GPIO_NUM_9
#define BOARD_ETH_SPI_HOST         SPI2_HOST

#define BOARD_SD_MOSI              GPIO_NUM_6
#define BOARD_SD_MISO              GPIO_NUM_5
#define BOARD_SD_SCLK              GPIO_NUM_7
#define BOARD_SD_CS                GPIO_NUM_4

#define BOARD_HAS_ETHERNET   1
#define BOARD_HAS_WIFI       1
#define BOARD_HAS_BLUETOOTH  1
#define BOARD_HAS_SD         1
#define BOARD_HAS_LORA_UART  1
#define BOARD_HAS_GNSS_UART  1
#define BOARD_ETHERNET_TYPE  BOARD_ETHERNET_TYPE_W5500
