#pragma once

#include "../board_caps.h"
#include "board_pins.h"

#define BOARD_NAME "Mammotion ESP32-S3 RTK"

#define BOARD_HAS_LORA_RADIO       1
#define BOARD_LORA_CHIP_LLCC68     1
#define BOARD_LORA_DRIVER_SX126X   1

#define DEFAULT_DEBUG_UART_NUM     BOARD_GNSS_DEBUG_UART_NUM
#define DEFAULT_DEBUG_UART_TX_PIN  BOARD_GNSS_DEBUG_UART_TX_PIN
#define DEFAULT_DEBUG_UART_RX_PIN  BOARD_GNSS_DEBUG_UART_RX_PIN
#define DEFAULT_DEBUG_UART_RTS_PIN GPIO_NUM_NC
#define DEFAULT_DEBUG_UART_CTS_PIN GPIO_NUM_NC

#define DEFAULT_GNSS_UART_NUM      BOARD_GNSS_UART_NUM
#define DEFAULT_GNSS_UART_TX_PIN   BOARD_GNSS_UART_TX_PIN
#define DEFAULT_GNSS_UART_RX_PIN   BOARD_GNSS_UART_RX_PIN
#define DEFAULT_GNSS_UART_RTS_PIN  GPIO_NUM_NC
#define DEFAULT_GNSS_UART_CTS_PIN  GPIO_NUM_NC

#define DEFAULT_AUX_UART_NUM       BOARD_GNSS_DEBUG_UART_NUM
#define DEFAULT_AUX_UART_TX_PIN    BOARD_GNSS_DEBUG_UART_TX_PIN
#define DEFAULT_AUX_UART_RX_PIN    BOARD_GNSS_DEBUG_UART_RX_PIN
#define DEFAULT_AUX_UART_RTS_PIN   GPIO_NUM_NC
#define DEFAULT_AUX_UART_CTS_PIN   GPIO_NUM_NC

#define BOARD_ETH_MOSI             BOARD_W5500_MOSI
#define BOARD_ETH_MISO             BOARD_W5500_MISO
#define BOARD_ETH_SCLK             BOARD_W5500_SCK
#define BOARD_ETH_CS               BOARD_W5500_CS
#define BOARD_ETH_INT              BOARD_W5500_INT
#define BOARD_ETH_RST              BOARD_W5500_RST
#define BOARD_ETH_SPI_HOST         BOARD_W5500_SPI_HOST

#define BOARD_SD_MOSI              BOARD_SD_CARD_MOSI
#define BOARD_SD_MISO              BOARD_SD_CARD_MISO
#define BOARD_SD_SCLK              BOARD_SD_CARD_SCK
#define BOARD_SD_CS                BOARD_SD_CARD_CS

#define BOARD_HAS_ETHERNET   0
#define BOARD_HAS_WIFI       1
#define BOARD_HAS_BLUETOOTH  1
#define BOARD_HAS_SD         0
#define BOARD_HAS_LORA_UART  0
#define BOARD_HAS_GNSS_UART  1

#define BOARD_NTRIP_MAX_SLOTS_NO_PSRAM 3
#define BOARD_NTRIP_MAX_SLOTS_PSRAM    4
