#pragma once

#include "sdkconfig.h"
#include "lora_region.h"

#define LORA_DEFAULT_SPI_CLOCK_HZ  8000000

#if CONFIG_LORA_REGION_EU868
#define LORA_DEFAULT_REGION LORA_REGION_EU868
#elif CONFIG_LORA_REGION_US915
#define LORA_DEFAULT_REGION LORA_REGION_US915
#elif CONFIG_LORA_REGION_AU915
#define LORA_DEFAULT_REGION LORA_REGION_AU915
#elif CONFIG_LORA_REGION_AS923
#define LORA_DEFAULT_REGION LORA_REGION_AS923
#elif CONFIG_LORA_REGION_CUSTOM
#define LORA_DEFAULT_REGION LORA_REGION_CUSTOM
#else
#define LORA_DEFAULT_REGION LORA_REGION_EU868
#endif

#if CONFIG_LORA_CHIP_FAMILY_SX1261
#define LORA_DEFAULT_CHIP_FAMILY LORA_CHIP_FAMILY_SX1261
#elif CONFIG_LORA_CHIP_FAMILY_SX1262
#define LORA_DEFAULT_CHIP_FAMILY LORA_CHIP_FAMILY_SX1262
#elif CONFIG_LORA_CHIP_FAMILY_SX1268
#define LORA_DEFAULT_CHIP_FAMILY LORA_CHIP_FAMILY_SX1268
#elif CONFIG_LORA_CHIP_FAMILY_LLCC68
#define LORA_DEFAULT_CHIP_FAMILY LORA_CHIP_FAMILY_LLCC68
#else
#define LORA_DEFAULT_CHIP_FAMILY LORA_CHIP_FAMILY_SX1262
#endif

#if CONFIG_LORA_RADIO_PROFILE_RTK_FAST
#define LORA_DEFAULT_RADIO_PROFILE LORA_RADIO_PROFILE_RTK_FAST
#elif CONFIG_LORA_RADIO_PROFILE_CUSTOM
#define LORA_DEFAULT_RADIO_PROFILE LORA_RADIO_PROFILE_CUSTOM
#else
#define LORA_DEFAULT_RADIO_PROFILE LORA_RADIO_PROFILE_RTK_FAST
#endif

#if CONFIG_LORA_RTCM_PROFILE_RTK_MINIMAL
#define LORA_DEFAULT_RTCM_PROFILE LORA_RTCM_PROFILE_RTK_MINIMAL
#elif CONFIG_LORA_RTCM_PROFILE_CUSTOM
#define LORA_DEFAULT_RTCM_PROFILE LORA_RTCM_PROFILE_CUSTOM
#else
#define LORA_DEFAULT_RTCM_PROFILE LORA_RTCM_PROFILE_RTK_MINIMAL
#endif

#define LORA_DEFAULT_FREQ_HZ       CONFIG_LORA_FREQUENCY_HZ
#define LORA_DEFAULT_SF            7U
#define LORA_DEFAULT_BW_HZ         500000UL
#define LORA_DEFAULT_CR            5U
#define LORA_DEFAULT_SYNC_WORD     0x12
#define LORA_DEFAULT_CRC_ON        true
#define LORA_DEFAULT_INVERT_IQ     false
#define LORA_DEFAULT_TX_POWER_DBM  CONFIG_LORA_TX_POWER_DBM
#define LORA_DEFAULT_PREAMBLE_LEN  8U
